import { SyncMode } from "./types.ts";

export const SYNCMODE_DEFAULT = SyncMode.Full;
export const DATADIR_DEFAULT = `./datadir`;
export const PORT_DEFAULT = 30303;
export const MAXPERREQUEST_DEFAULT = 100;
export const MAXFETCHERJOBS_DEFAULT = 100;
export const MAXFETCHERREQUESTS_DEFAULT = 5;
export const MINPEERS_DEFAULT = 1;
export const MAXPEERS_DEFAULT = 25;
export const EXECUTION = true;
export const NUM_BLOCKS_PER_ITERATION = 100;
export const ACCOUNT_CACHE = 400000;
export const STORAGE_CACHE = 200000;
export const CODE_CACHE = 200000;
export const TRIE_CACHE = 200000;
export const DEBUGCODE_DEFAULT = false;
export const SAFE_REORG_DISTANCE = 100;
export const SYNCED_STATE_REMOVAL_PERIOD = 60000;
export const TX_LOOKUP_LIMIT_DEFAULT = 2350000;
